method: bayes
metric:
  goal: maximize
  name: eval/micro f1 score
parameters:
  batch_size:
    distribution: int_uniform
    max: 64
    min: 32
  # epochs:
  #   distribution: int_uniform
  #   max: 10
  #   min: 4
  freeze:
    distribution: int_uniform
    max: 201
    min: 1
  gradient_accumulation_steps:
    distribution: int_uniform
    max: 4
    min: 1
  learning_rate:
    distribution: uniform
    max: 1e-04
    min: 1e-05
  # dropout:
  #   distribution: uniform
  #   max: 0.5
  #   min: 0.1
program: train-freze.py