program: train-wandb.py
method: bayes
metric:
  goal: maximize
  name: eval/micro f1 score
parameters: 
  gradient_accumulation_steps:
    max: 8
    min: 1
    distribution: int_uniform
  epochs :
    max: 40
    min: 5
    distribution: int_uniform
  learning_rate :
    max: 0.0001
    min: 0.000001
    distribution: uniform
  batch_size :
    max: 6
    min: 5
    distribution: int_uniform

    
